commit

diff --git a/sd-burner b/sd-burner
--- a/sd-burner
+++ b/sd-burner
@@ -6,37 +6,43 @@
 # 
 
 source modules.sh
+source save_image.sh
 
 while [ -n "$1" ]
 do
     case "$1" in
-        -c | --clean)
-          shift 
-                    erase_sd "$1"
-                    ;;
-        -l | --list)
-                    lsblk
-                    ;;
-        -b | --burn)
-                    shift
-          # burn_sd <device_name> <image_name>
-                    burn_sd "$1" "$2"
-                    shift
-         ;;  
-    -d | --download)
-      shift
-      # download_and_burn_image /dev/sda 124 
-      download_and_burn_image "$1" "$2"
-      shift
-      ;;
-    -h | --help)
-      sdburner_help
-      ;;
-    *)
-      echo "error: "$1" is not a valid input"
-      sdburner_help
-      exit 1
-      ;;
+						-c | --clean)
+								shift 
+								erase_sd "$1"
+								;;
+						-l | --list)
+																		lsblk
+																		;;
+						-b | --burn)
+								shift
+								# burn_sd <device_name> <image_name>
+								burn_sd "$1" "$2"
+								shift
+				   	;;  
+						-d | --download)
+								shift
+								# download_and_burn_image /dev/sda 124 
+								download_and_burn_image "$1" "$2"
+								shift
+								;;
+						-h | --help)
+								sdburner_help
+								;;
+      --save)
+        shift
+        save_image "$1" "$2"
+        shift
+        ;; 
+						*)
+								echo "error: "$1" is not a valid input"
+								sdburner_help
+								exit 1
+								;;
     esac   
   shift
 done
